name: vertex_app
description: A comprehensive super app for college students
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  app_links: ^6.4.0
  go_router: ^14.0.0


  # UI enhancements

  flutter_svg: ^2.0.7
  cached_network_image: ^3.4.1

  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.1.14

  # State management
  carousel_slider: ^5.0.0
  video_player: ^2.9.5
  chewie: ^1.11.0
  percent_indicator: ^4.2.4
  shimmer: ^3.0.0
  confetti: ^0.8.0
  animations: ^2.0.11
  lottie: ^3.3.1
  story_view: ^0.16.5
  like_button: ^2.0.5
  flutter_staggered_grid_view: ^0.7.0
  photo_view: ^0.15.0
  timeago: ^3.7.0
  flutter_native_splash: ^2.4.5

  #firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vertex_logo.jpg
    - assets/icons/
    - assets/sammy-line-man-receives-a-mail.png

flutter_native_splash:
  color: "#ffffff" # Background color
  image: lib/assets/vertex_logo.jpg
  android: true
  ios: true
  fullscreen: true
