// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC9NJm1VUn1SDR6KjxOZJWbdavhsGcxJM',
    appId: '1:748216728873:web:9382c0bd760ecddc768b38',
    messagingSenderId: '748216728873',
    projectId: 'vynk-24bfd',
    authDomain: 'vynk-24bfd.firebaseapp.com',
    storageBucket: 'vynk-24bfd.firebasestorage.app',
    measurementId: 'G-PG05GYZTGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj0qskWJKWgq_5aYKyu2PK8gANDxgZMDI',
    appId: '1:748216728873:android:a1da76f0cf36f5e7768b38',
    messagingSenderId: '748216728873',
    projectId: 'vynk-24bfd',
    storageBucket: 'vynk-24bfd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7wu3UoU-14cUW9iBh06EMz0wCRRcAjjo',
    appId: '1:748216728873:ios:e676f3ddbb4477cc768b38',
    messagingSenderId: '748216728873',
    projectId: 'vynk-24bfd',
    storageBucket: 'vynk-24bfd.firebasestorage.app',
    androidClientId: '748216728873-off8vaq6hfa4dfor9jedfpb0du88c1ik.apps.googleusercontent.com',
    iosClientId: '748216728873-jbnam0uqel3nlos8gnij1att4sop13k9.apps.googleusercontent.com',
    iosBundleId: 'com.example.vertexApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7wu3UoU-14cUW9iBh06EMz0wCRRcAjjo',
    appId: '1:748216728873:ios:e676f3ddbb4477cc768b38',
    messagingSenderId: '748216728873',
    projectId: 'vynk-24bfd',
    storageBucket: 'vynk-24bfd.firebasestorage.app',
    androidClientId: '748216728873-off8vaq6hfa4dfor9jedfpb0du88c1ik.apps.googleusercontent.com',
    iosClientId: '748216728873-jbnam0uqel3nlos8gnij1att4sop13k9.apps.googleusercontent.com',
    iosBundleId: 'com.example.vertexApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC9NJm1VUn1SDR6KjxOZJWbdavhsGcxJM',
    appId: '1:748216728873:web:c93b55513133a227768b38',
    messagingSenderId: '748216728873',
    projectId: 'vynk-24bfd',
    authDomain: 'vynk-24bfd.firebaseapp.com',
    storageBucket: 'vynk-24bfd.firebasestorage.app',
    measurementId: 'G-QEFWY4KGN9',
  );
}
